os: linux
arch:
 - amd64
 - ppc64le
sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - python tests.py
